---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.4
  - 2.2.3
  - 2.2.2
  - head
env:
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=head"
